repos:
  - repo: https://github.com/psf/black 
    rev: 24.3.0  # versão do Black
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort 
    rev: 5.12.0  # versão do isort
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8 
    rev: 6.1.0  # versão do flake8
    hooks:
      - id: flake8